INSERT INTO member (name, age) VALUES ('Bill', 10);
INSERT INTO member (name, age) VALUES ('Kz', 5);

INSERT INTO MEAL (MEAL_NAME, PRICE, DESCRIPTION) VALUES ('可樂', 39, '百事可樂最好喝');
INSERT INTO MEAL (MEAL_NAME, PRICE, DESCRIPTION) VALUES ('麥香魚', 49, '萬般皆下品，唯有魚最高');
INSERT INTO MEAL (MEAL_NAME, PRICE, DESCRIPTION) VALUES ('辣味雞腿套餐', 160, '我先炸好再炸一次');

INSERT INTO RESTAURANT_ORDER (WAITER) VALUES ('墮胎叔叔');
